version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management 
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
      - 8080:8080 
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - makonskaitlosana
  minio:
      image: bitnami/minio
      container_name: 'minio'
      volumes:
        - ./volumes/minio/data:/data
      ports:
        - 9000:9000
        - 9001:9001
      environment:
        - MINIO_ROOT_USER=rootUser
        - MINIO_ROOT_PASSWORD=rootUser
      networks:
        - makonskaitlosana
  openalpr:
    build: ./openalpr
    container_name: 'openalpr'
    restart: on-failure
    volumes:
        - ./openalpr/source/index.js:/source/index.js
    ports:
      - "3001:3000"
    networks:
      - makonskaitlosana
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    logging:
      driver: 'none'
    networks:
      - makonskaitlosana
    ports:
      - 1025:1025 
      - 8025:8025 
  db:
    image: mysql
    container_name: 'db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - makonskaitlosana
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
  app:
    build: .
    container_name: 'app'
    restart: on-failure
    volumes:
        - ./source/index.js:/source/index.js
    networks:
      - makonskaitlosana
    ports:
      - "3000:3000"
networks:
    makonskaitlosana:
      driver: bridge  
volumes:
  mysql_db_data_container:
