FROM  openalpr/openalpr:latest

WORKDIR /source
COPY source /source
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install nodejs
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
RUN npm install -g npm@9.2.0
RUN npm install
HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost:3000 || exit 1
ENTRYPOINT [ "node", "index.js" ]
